In [1]:
print("jupyter working ")

jupyter working

In [2]:
!uv add numpy pandas openpyxl

Resolved 40 packages in 2ms
Audited 6 packages in 0.86ms

In [3]:
import numpy as np 
import pandas as pd 
import openpyxl as op

In [14]:
df = pd.read_excel("../data/sample.xlsx", sheet_name="MON", header=3, index_col=0)

In [42]:
df.head()

,Docket No,Reg No,Mobile,Gender,TIME,Service,CASH,CARD,RSL,GV,...,Unnamed: 34,Unnamed: 35,GA machine,BLH machine.2,Wongo.2,Unnamed: 39,Unnamed: 40,GA machine.1,BLH machine.3,Wongo.3
No,,,,,,,,,,,,,,,,,,,,,
1,14125,KEN838,0412038383,M,905,PCL,NaN,NaN,0,79,...,NOV,1.0,NaN,NaN,NaN,NaN,16,NaN,NaN,NaN
2,14126,ENA66S,0416951959,F,915,PCL,NaN,NaN,0,79,...,NaN,2.0,NaN,NaN,NaN,NaN,17,NaN,NaN,NaN
3,14127,EEY61G,0401995714,F,930,X,95,NaN,0,0,...,NaN,3.0,NaN,NaN,NaN,NaN,18,NaN,NaN,NaN
4,14128,CN800,0418882000,F,935,D,NaN,75,0,0,...,NaN,4.0,NaN,NaN,NaN,NaN,19,NaN,NaN,NaN
5,14129,JH2211,0412771876,F,945,X,NaN,95,0,0,...,NaN,5.0,NaN,NaN,NaN,NaN,20,NaN,NaN,NaN

In [43]:
df.iloc[0:21, 0:14]

,Docket No,Reg No,Mobile,Gender,TIME,Service,CASH,CARD,RSL,GV,GV CASH,GV CARD,O/Taker,Comment
No,,,,,,,,,,,,,,
1,14125,KEN838,0412038383,M,905,PCL,NaN,NaN,0,79,NaN,NaN,HENDRA,22012 (6/6)
2,14126,ENA66S,0416951959,F,915,PCL,NaN,NaN,0,79,NaN,475,HENDRA,23225 (1/6)
3,14127,EEY61G,0401995714,F,930,X,95,NaN,0,0,NaN,NaN,HENDRA,NaN
4,14128,CN800,0418882000,F,935,D,NaN,75,0,0,NaN,NaN,HENDRA,NaN
5,14129,JH2211,0412771876,F,945,X,NaN,95,0,0,NaN,NaN,HENDRA,NaN
6,14130,CE32DD,0416155783,F,1010,D,NaN,75,0,0,NaN,NaN,SHIVAM,NaN
7,14131,EVU18U,0499080777,F,1030,GV,NaN,NaN,0,0,300,NaN,SHIVAM,XD-50-176 TO 181
8,14132,EXD61Y,0407213067,F,1050,D,NaN,75,0,0,NaN,NaN,SHIVAM,NaN
9,14133,DTY90V,0439592230,M,1100,H,NaN,100,0,0,NaN,NaN,SHIVAM,NaN
10,14134,NXQ74D,0408518552,F,1100,X,75,NaN,0,0,NaN,NaN,SHIVAM,NaN
11,14135,ERF78A,0432015255,F,1100,PCL,NaN,NaN,0,125,NaN,NaN,SHIVAM,22044 (4/6) H
12,14136,EUP53B,0410043981,F,1115,X,NaN,75,0,0,NaN,NaN,SHIVAM,NaN
13,14137,EKR80D,0414337002,M,1145,W/O,NaN,65,0,0,NaN,NaN,SHIVAM,NaN
14,14138,EBT61V,0416281895,F,1145,D,NaN,55,0,0,NaN,NaN,SHIVAM,NaN
15,14139,VW278,0417674600,F,1205,H,115,NaN,0,0,NaN,NaN,HENDRA,$5 OFF
16,14140,C1092M,0423229668,F,1325,X,NaN,120,0,0,NaN,NaN,HENDRA,DUST
17,14141,JKD988,0412822216,M,1330,PCL,NaN,NaN,0,79,NaN,NaN,SHIVAM,22186(2/6)
18,14142,DLY25Y,0421050164,M,1400,W/O,NaN,65,0,0,NaN,NaN,SHIVAM,NaN
19,14143,CV57AO,0435117046,F,1415,D,NaN,55,0,0,NaN,NaN,HENDRA,NaN
20,14144,DYZ80J,0481215048,F,1420,PCS,NaN,NaN,0,63,NaN,NaN,HENDRA,22056(1/6)
21,14145,DWR91W,0411724816,M,1500,X,NaN,95,0,0,NaN,NaN,VINNY,NaN

In [47]:
df_split = df.iloc[0: 64, 0: 14]

In [55]:
df_data = df_split[df_split['Docket No'].notna()].reset_index(drop=True)

In [56]:
df_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Docket No  23 non-null     object
 1   Reg No     23 non-null     object
 2   Mobile     23 non-null     str
 3   Gender     23 non-null     str
 4   TIME       23 non-null     object
 5   Service    23 non-null     str
 6   CASH       5 non-null      object
 7   CARD       14 non-null     object
 8   RSL        23 non-null     object
 9   GV         23 non-null     object
 10  GV CASH    3 non-null      object
 11  GV CARD    3 non-null      object
 12  O/Taker    23 non-null     object
 13   Comment   10 non-null     object
dtypes: object(11), str(3)
memory usage: 2.6+ KB

In [57]:
df_data = df_data[df_data['Docket No'] != 'Docket No'].reset_index(drop=True)

In [60]:
df_data

,Docket No,Reg No,Mobile,Gender,TIME,Service,CASH,CARD,RSL,GV,GV CASH,GV CARD,O/Taker,Comment
0,14125,KEN838,0412038383,M,905,PCL,NaN,NaN,0,79,NaN,NaN,HENDRA,22012 (6/6)
1,14126,ENA66S,0416951959,F,915,PCL,NaN,NaN,0,79,NaN,475,HENDRA,23225 (1/6)
2,14127,EEY61G,0401995714,F,930,X,95,NaN,0,0,NaN,NaN,HENDRA,NaN
3,14128,CN800,0418882000,F,935,D,NaN,75,0,0,NaN,NaN,HENDRA,NaN
4,14129,JH2211,0412771876,F,945,X,NaN,95,0,0,NaN,NaN,HENDRA,NaN
5,14130,CE32DD,0416155783,F,1010,D,NaN,75,0,0,NaN,NaN,SHIVAM,NaN
6,14131,EVU18U,0499080777,F,1030,GV,NaN,NaN,0,0,300,NaN,SHIVAM,XD-50-176 TO 181
7,14132,EXD61Y,0407213067,F,1050,D,NaN,75,0,0,NaN,NaN,SHIVAM,NaN
8,14133,DTY90V,0439592230,M,1100,H,NaN,100,0,0,NaN,NaN,SHIVAM,NaN
9,14134,NXQ74D,0408518552,F,1100,X,75,NaN,0,0,NaN,NaN,SHIVAM,NaN
10,14135,ERF78A,0432015255,F,1100,PCL,NaN,NaN,0,125,NaN,NaN,SHIVAM,22044 (4/6) H
11,14136,EUP53B,0410043981,F,1115,X,NaN,75,0,0,NaN,NaN,SHIVAM,NaN
12,14137,EKR80D,0414337002,M,1145,W/O,NaN,65,0,0,NaN,NaN,SHIVAM,NaN
13,14138,EBT61V,0416281895,F,1145,D,NaN,55,0,0,NaN,NaN,SHIVAM,NaN
14,14139,VW278,0417674600,F,1205,H,115,NaN,0,0,NaN,NaN,HENDRA,$5 OFF
15,14140,C1092M,0423229668,F,1325,X,NaN,120,0,0,NaN,NaN,HENDRA,DUST
16,14141,JKD988,0412822216,M,1330,PCL,NaN,NaN,0,79,NaN,NaN,SHIVAM,22186(2/6)
17,14142,DLY25Y,0421050164,M,1400,W/O,NaN,65,0,0,NaN,NaN,SHIVAM,NaN
18,14143,CV57AO,0435117046,F,1415,D,NaN,55,0,0,NaN,NaN,HENDRA,NaN
19,14144,DYZ80J,0481215048,F,1420,PCS,NaN,NaN,0,63,NaN,NaN,HENDRA,22056(1/6)
20,14145,DWR91W,0411724816,M,1500,X,NaN,95,0,0,NaN,NaN,VINNY,NaN

In [54]:
df_selected['Docket No'] = pd.to_numeric(df_data['Docket No'], errors='coerce')

NameError: name 'df_selected' is not defined

In [31]:
def extract_tables(df):
    # Check table 1 (rows 1-25)
    table1 = df.iloc[1:26]  # Rows 1-25
    table1_data = table1[table1['Docket No'].notna()]
    
    # Check if table 2 has data (look at rows 35+)
    has_table2 = df.iloc[35:]['Docket No'].notna().any()
    
    if has_table2:
        table2 = df.iloc[35:60]  # Rows 35-59 (25 rows)
        table2_data = table2[table2['Docket No'].notna()]
        return table1_data, table2_data
    else:
        return table1_data, None

table1_data, table2_data = extract_tables(df)

In [36]:
table1_data['Docket No.']

KeyError: 'Docket No.'